service: user-dynamo-app

provider:
 name: aws
 runtime: nodejs14.x
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
   - Effect: Allow
     Action: 
       - dynamodb:DescribeTable
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
     Resource:
       - { "Fn::GetAtt": ["UserTable", "Arn"]}
 environment:
   NODE_ENV: production

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY /{proxy+}
     - http: ANY /
resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: userInfo